# Generated by Django 4.0.1 on 2022-02-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_comment_author_alter_comment_body_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_articles', to='newsapp.post', verbose_name='Статья'),
        ),
    ]
